# TMDB Movie Data Analysis using Pandas and APIs

---

## Project Overview

This project challenges you to build a movie data analysis pipeline using Python and Pandas. You will fetch movie-related data from an API, clean and transform the dataset, and implement key performance indicators (KPIs).

This is not a group project, meaning you will design the workflow, structure the analysis, and implement the required calculations independently.

---

## Project Objectives

- **API Data Extraction:** Fetch movie data from a movie database API
- **Data Cleaning & Transformation:** Process and structure the data for analysis
- **Exploratory Data Analysis (EDA):** Perform an initial exploration to understand trends
- **Advanced Filtering & Ranking:** Identify the best and worst movies based on financial and popularity metrics
- **Franchise & Director Analysis:** Assess how franchises and directors perform over time
- **Visualization & Insights:** Present key findings using visualizations

---

In [1]:
# Import the libraries that we will use throughout the project
import os
import requests
import pandas as pd
import numpy as np
from dotenv import load_dotenv

## Project Steps

### Step 1: Fetch Movie Data from API

- Choose a movie database API (e.g., TMDb)
- Fetch movies with the following IDs:

```python
movie_id = [
    0, 299534, 19995, 140607, 299536, 597, 135397,
    420818, 24428, 168259, 99861, 284054, 12445,
    181808, 330457, 351286, 109445, 321612, 260513
]
```

- Store the data as a Pandas DataFrame

> **NB:** Read the API documentation to understand the nature of the data and how it's organized.

---

In [2]:
# Getting the api token stored in our .env file
load_dotenv()
TOKEN = os.getenv("API_READ_ACCESS_TOKEN")
# incase the token is missing:
if not TOKEN:
    raise ValueError("API_READ_ACCESS_TOKEN is missing from your .env file.")

# Collection of movie ids whose data we will use for the project
movie_collection = [
    0, 299534, 19995, 140607, 299536, 597, 135397,
    420818, 24428, 168259, 99861, 284054, 12445,
    181808, 330457, 351286, 109445, 321612, 260513
]

movies = []

# Loop through the api url using each "movie id"
for movie_id in movie_collection:
    url = f"https://api.themoviedb.org/3/movie/{movie_id}?language=en-US"
    try:
        # The header where the token is applied
        headers = {
            "accept": "application/json",
            "Authorization": f"Bearer {TOKEN}"
        }
        # the response from the api
        response = requests.get(url, headers=headers)
        # convert the response to json
        movie_data = response.json()
        # save the data to our list
        movies.append(response.json())
        print(f"Fetched: {movie_data.get('title', movie_id)}")
        
    except requests.exceptions.HTTPError as error:
        print(f"Could not fetch movie ID {movie_id}: {error}")

    except requests.exceptions.RequestException as error:
        print(f"Request failed for movie ID {movie_id}: {error}")

# Convert the list of dictionaries into a DataFrame
df = pd.DataFrame(movies)

Fetched: 0
Fetched: Avengers: Endgame
Fetched: Avatar
Fetched: Star Wars: The Force Awakens
Fetched: Avengers: Infinity War
Fetched: Titanic
Fetched: Jurassic World
Fetched: The Lion King
Fetched: The Avengers
Fetched: Furious 7
Fetched: Avengers: Age of Ultron
Fetched: Black Panther
Fetched: Harry Potter and the Deathly Hallows: Part 2
Fetched: Star Wars: The Last Jedi
Fetched: Frozen II
Fetched: Jurassic World: Fallen Kingdom
Fetched: Frozen
Fetched: Beauty and the Beast
Fetched: Incredibles 2

In [3]:
# Drop the first row, since the API failed to retrieve it (movie id = 0)
df = df.drop(df.index[0]).reset_index(drop=True)

In [4]:
df.head()

,success,status_code,status_message,adult,backdrop_path,belongs_to_collection,budget,genres,homepage,id,...,revenue,runtime,softcore,spoken_languages,status,tagline,title,video,vote_average,vote_count
0,NaN,NaN,NaN,False,/7RyHsO4yDXtBv1zUU3mTpHeQ0d5.jpg,"{'id': 86311, 'name': 'The Avengers Collection...",356000000.0,"[{'id': 12, 'name': 'Adventure'}, {'id': 878, ...",https://www.marvel.com/movies/avengers-endgame,299534.0,...,2.927449e+09,181.0,False,"[{'english_name': 'English', 'iso_639_1': 'en'...",Released,Avenge the fallen.,Avengers: Endgame,False,8.200,28977.0
1,NaN,NaN,NaN,False,/vL5LR6WdxWPjLPFRLe133jXWsh5.jpg,"{'id': 87096, 'name': 'Avatar Collection', 'po...",237000000.0,"[{'id': 878, 'name': 'Science Fiction'}, {'id'...",https://www.avatar.com/movies/avatar,19995.0,...,2.923706e+09,162.0,False,"[{'english_name': 'English', 'iso_639_1': 'en'...",Released,Enter the world of Pandora.,Avatar,False,7.600,34826.0
2,NaN,NaN,NaN,False,/8BTsTfln4jlQrLXUBquXJ0ASQy9.jpg,"{'id': 10, 'name': 'Star Wars Collection', 'po...",245000000.0,"[{'id': 12, 'name': 'Adventure'}, {'id': 28, '...",http://www.starwars.com/films/star-wars-episod...,140607.0,...,2.068224e+09,136.0,False,"[{'english_name': 'English', 'iso_639_1': 'en'...",Released,Every generation has a story.,Star Wars: The Force Awakens,False,7.240,21003.0
3,NaN,NaN,NaN,False,/mDfJG3LC3Dqb67AZ52x3Z0jU0uB.jpg,"{'id': 86311, 'name': 'The Avengers Collection...",300000000.0,"[{'id': 12, 'name': 'Adventure'}, {'id': 28, '...",https://www.marvel.com/movies/avengers-infinit...,299536.0,...,2.052415e+09,149.0,False,"[{'english_name': 'English', 'iso_639_1': 'en'...",Released,An entire universe. Once and for all.,Avengers: Infinity War,False,8.245,33133.0
4,NaN,NaN,NaN,False,/xXCuto8YVp5RFqBJ7yKmVmLOWpF.jpg,None,200000000.0,"[{'id': 18, 'name': 'Drama'}, {'id': 10749, 'n...",https://www.paramountmovies.com/movies/titanic,597.0,...,2.264162e+09,194.0,False,"[{'english_name': 'English', 'iso_639_1': 'en'...",Released,Nothing on earth could come between them.,Titanic,False,7.900,27878.0

### Step 2: Data Cleaning and Preprocessing

#### Data Preparation & Cleaning

1. Drop irrelevant columns: `['adult', 'imdb_id', 'original_title', 'video', 'homepage']`

In [5]:
df = df.drop(columns=['adult', 'imdb_id', 'original_title', 'video', 'homepage', 'backdrop_path', 'poster_path', "success", "status_code", "status_message"])
df.columns

Index(['belongs_to_collection', 'budget', 'genres', 'id', 'origin_country',
       'original_language', 'overview', 'popularity', 'production_companies',
       'production_countries', 'release_date', 'revenue', 'runtime',
       'softcore', 'spoken_languages', 'status', 'tagline', 'title',
       'vote_average', 'vote_count'],
      dtype='str')

2. Evaluate JSON-like columns: `['belongs_to_collection', 'genres', 'production_countries', 'production_companies', 'spoken_languages']`
3. Extract and clean key data points:
   - Collection name (`belongs_to_collection`)

In [6]:
df["belongs_to_collection"][1]

{'id': 87096,
 'name': 'Avatar Collection',
 'poster_path': '/3C5brXxnBxfkeKWwA1Fh4xvy4wr.jpg',
 'backdrop_path': '/4uwX70EzaWVcGUXMtXPoexlNAff.jpg'}

In [7]:
# Extract the dictionary keys into a temporary dataframe
collection_df = df['belongs_to_collection'].apply(pd.Series)

# Rename the columns into the new desired format
collection_df = collection_df.rename(columns={
    'id': 'collection_id',
    'name': 'collection_name',
    'poster_path': 'collection_poster_path',
    'backdrop_path': 'collection_backdrop_path'
})

# Join the new columns back to the original dataframe (exclude "collection_poster_path" and "collection_backdrop_path")
df = pd.concat([df, collection_df[['collection_id', 'collection_name']]], axis=1)

# Drop the uncleaned column now that the new clean columns have been added
df = df.drop(columns=["belongs_to_collection"])

   - Genre names (`genres` → separate multiple genres with `|`)
   - Spoken languages (`spoken_languages` → separate with `|`)
   - Production countries (`production_countries` → separate with `|`)
   - Production companies (`production_companies` → separate with `|`)

In [8]:
df["production_countries"][3]

[{'iso_3166_1': 'US', 'name': 'United States of America'}]

In [9]:
# Create function to join the names inside the columns
def clean_names(column):
    if isinstance(column, list):
        names = []

        for name in column:
            names.append(name["name"])

        return "|".join(names)

    else:
        return None

In [10]:
#use function to clean names
df["genres"] = df["genres"].apply(clean_names)
df["spoken_languages"] = df["spoken_languages"].apply(clean_names)
df["production_countries"] = df["production_countries"].apply(clean_names)
df["production_companies"] = df["production_companies"].apply(clean_names)

In [11]:
df["spoken_languages"].head()

0                                         English|日本語|
1                                      English|Español
2                                              English
3                                             English|
4    English|Français|Deutsch|svenska|Italiano|Pусский
Name: spoken_languages, dtype: str

4. Inspect extracted columns using `value_counts()` to identify anomalies

In [12]:
# Apply value_counts() to every column:
for i in df.columns:
    print(df[f"{i}"].value_counts())
    print("-----------------------------------")

budget
200000000.0    3
150000000.0    3
300000000.0    2
356000000.0    1
237000000.0    1
245000000.0    1
260000000.0    1
220000000.0    1
190000000.0    1
235000000.0    1
125000000.0    1
170000000.0    1
160000000.0    1
Name: count, dtype: int64
-----------------------------------
genres
Adventure|Action|Science Fiction             3
Science Fiction|Action|Adventure             2
Adventure|Science Fiction|Thriller           2
Action|Adventure|Science Fiction             2
Adventure|Science Fiction|Action             1
Drama|Romance                                1
Adventure|Drama|Family|Animation             1
Action|Crime|Thriller                        1
Adventure|Fantasy                            1
Family|Animation|Adventure|Comedy|Fantasy    1
Animation|Family|Adventure|Fantasy           1
Family|Fantasy|Romance                       1
Action|Adventure|Animation|Family            1
Name: count, dtype: int64
-----------------------------------
id
299534.0    1
19995.0     1
140607.0    1
299536.0    1
597.0       1
135397.0    1
420818.0    1
24428.0     1
168259.0    1
99861.0     1
284054.0    1
12445.0     1
181808.0    1
330457.0    1
351286.0    1
109445.0    1
321612.0    1
260513.0    1
Name: count, dtype: int64
-----------------------------------
origin_country
[US]    17
[GB]     1
Name: count, dtype: int64
-----------------------------------
original_language
en    18
Name: count, dtype: int64
-----------------------------------
overview
After the devastating events of Avengers: Infinity War, the universe is in ruins due to the efforts of the Mad Titan, Thanos. With the help of remaining allies, the Avengers must assemble once more in order to undo Thanos' actions and restore order to the universe once and for all, no matter what consequences may be in store.                                                                                                                                                                                                                                            1
In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization.                                                                                                                                                                                                                                                                                                                                                                                                    1
Thirty years after defeating the Galactic Empire, Han Solo and his allies face a new threat from the evil Kylo Ren and his army of Stormtroopers.                                                                                                                                                                                                                                                                                                                                                                                                                                  1
As the Avengers and their allies have continued to protect the world from threats too large for any one hero to handle, a new danger has emerged from the cosmic shadows: Thanos. A despot of intergalactic infamy, his goal is to collect all six Infinity Stones, artifacts of unimaginable power, and use them to inflict his twisted will on all of reality. Everything the Avengers have fought for has led up to this moment - the fate of Earth and existence itself has never been more uncertain.                                                                         1
101-year-old Rose DeWitt Bukater tells the story of her life aboard the Titanic, 84 years later. A young Rose boards the ship with her mother and fiancé. Meanwhile, Jack Dawson and Fabrizio De Rossi win third-class tickets aboard the ship. Rose tells the whole story from Titanic's departure through to its death—on its first and last voyage—on April 15, 1912.                                                                                                                                                                                                           1
Twenty-two years after the events of Jurassic Park, Isla Nublar now features a fully functioning dinosaur theme park, Jurassic World, as originally envisioned by John Hammond.                                                                                                                                                                                                                                                                                                                                                                                                    1
Simba idolizes his father, King Mufasa, and takes to heart his own royal destiny. But not everyone in the kingdom celebrates the new cub's arrival. Scar, Mufasa's brother—and former heir to the throne—has plans of his own. The battle for Pride Rock is ravaged with betrayal, tragedy and drama, ultimately resulting in Simba's exile. With help from a curious pair of newfound friends, Simba will have to figure out how to grow up and take back what is rightfully his.                                                                                                 1
When an unexpected enemy emerges and threatens global safety and security, Nick Fury, director of the international peacekeeping agency known as S.H.I.E.L.D., finds himself in need of a team to pull the world back from the brink of disaster. Spanning the globe, a daring recruitment effort begins!                                                                                                                                                                                                                                                                          1
Deckard Shaw seeks revenge against Dominic Toretto and his family for his comatose brother.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        1
When Tony Stark tries to jumpstart a dormant peacekeeping program, things go awry and Earth’s Mightiest Heroes are put to the ultimate test as the fate of the planet hangs in the balance. As the villainous Ultron emerges, it is up to The Avengers to stop him from enacting his terrible plans, and soon uneasy alliances and unexpected action pave the way for an epic and unique global adventure.                                                                                                                                                                         1
King T'Challa returns home to the reclusive, technologically advanced African nation of Wakanda to serve as his country's new leader. However, T'Challa soon finds that he is challenged for the throne by factions within his own country as well as without. Using powers reserved to Wakandan kings, T'Challa assumes the Black Panther mantle to join with ex-girlfriend Nakia, the queen-mother, his princess-kid sister, members of the Dora Milaje (the Wakandan 'special forces') and an American secret agent, to prevent Wakanda from being dragged into a world war.    1
Harry, Ron and Hermione continue their quest to vanquish the evil Voldemort once and for all. Just as things begin to look hopeless for the young wizards, Harry discovers a trio of magical objects that endow him with powers to rival Voldemort's formidable skills.                                                                                                                                                                                                                                                                                                            1
Rey develops her newly discovered abilities with the guidance of Luke Skywalker, who is unsettled by the strength of her powers. Meanwhile, the Resistance prepares to do battle with the First Order.                                                                                                                                                                                                                                                                                                                                                                             1
Elsa, Anna, Kristoff and Olaf head far into the forest to learn the truth about an ancient mystery of their kingdom.                                                                                                                                                                                                                                                                                                                                                                                                                                                               1
Three years after Jurassic World was destroyed, Isla Nublar now sits abandoned. When the island's dormant volcano begins roaring to life, Owen and Claire mount a campaign to rescue the remaining dinosaurs from this extinction-level event.                                                                                                                                                                                                                                                                                                                                     1
Young princess Anna of Arendelle dreams about finding true love at her sister Elsa’s coronation. Fate takes her on a dangerous journey in an attempt to end the eternal winter that has fallen over the kingdom. She's accompanied by ice delivery man Kristoff, his reindeer Sven, and snowman Olaf. On an adventure where she will find out what friendship, courage, family, and true love really means.                                                                                                                                                                        1
A live-action adaptation of Disney's version of the classic tale of a cursed prince and a beautiful young woman who helps him break the spell.                                                                                                                                                                                                                                                                                                                                                                                                                                     1
Elastigirl springs into action to save the day, while Mr. Incredible faces his greatest challenge yet – taking care of the problems of his three children.                                                                                                                                                                                                                                                                                                                                                                                                                         1
Name: count, dtype: int64
-----------------------------------
popularity
96.8577    1
41.8923    1
25.1323    1
93.1399    1
39.3321    1
26.8876    1
31.7892    1
66.0038    1
27.6625    1
49.2888    1
35.4211    1
42.1760    1
28.3074    1
30.4925    1
18.1120    1
29.2973    1
45.3530    1
27.8965    1
Name: count, dtype: int64
-----------------------------------
production_companies
Marvel Studios                                                                          5
Walt Disney Animation Studios                                                           2
Dune Entertainment|Lightstorm Entertainment|20th Century Fox|Ingenious Film Partners    1
Lucasfilm Ltd.|Bad Robot                                                                1
Paramount Pictures|20th Century Fox|Lightstorm Entertainment                            1
Amblin Entertainment|Universal Pictures|Legendary Pictures                              1
Walt Disney Pictures|Fairview Entertainment                                             1
Original Film|One Race|Universal Pictures                                               1
Warner Bros. Pictures|Heyday Films                                                      1
Lucasfilm Ltd.                                                                          1
Amblin Entertainment|Universal Pictures                                                 1
Walt Disney Pictures|Mandeville Films                                                   1
Pixar                                                                                   1
Name: count, dtype: int64
-----------------------------------
production_countries
United States of America                   16
United States of America|United Kingdom     1
United Kingdom|United States of America     1
Name: count, dtype: int64
-----------------------------------
release_date
2019-04-24    1
2009-12-16    1
2015-12-15    1
2018-04-25    1
1997-12-18    1
2015-06-06    1
2019-07-12    1
2012-04-25    1
2015-04-01    1
2015-04-22    1
2018-02-13    1
2011-07-12    1
2017-12-13    1
2019-11-20    1
2018-06-06    1
2013-11-20    1
2017-03-16    1
2018-06-14    1
Name: count, dtype: int64
-----------------------------------
revenue
2.927449e+09    1
2.923706e+09    1
2.068224e+09    1
2.052415e+09    1
2.264162e+09    1
1.671537e+09    1
1.662021e+09    1
1.518816e+09    1
1.515400e+09    1
1.405404e+09    1
1.349926e+09    1
1.341511e+09    1
1.334408e+09    1
1.453683e+09    1
1.310469e+09    1
1.274219e+09    1
1.266116e+09    1
1.243226e+09    1
Name: count, dtype: int64
-----------------------------------
runtime
118.0    2
129.0    2
181.0    1
162.0    1
136.0    1
149.0    1
194.0    1
124.0    1
143.0    1
138.0    1
141.0    1
135.0    1
130.0    1
152.0    1
103.0    1
102.0    1
Name: count, dtype: int64
-----------------------------------
softcore
False    18
Name: count, dtype: int64
-----------------------------------
spoken_languages
English                                              9
English|日本語|                                         1
English|Español                                      1
English|                                             1
English|Français|Deutsch|svenska|Italiano|Pусский    1
English|हिन्दी|Pусский                               1
العربية|English|Español|ภาษาไทย                      1
English|한국어/조선말|Kiswahili|                           1
English|Pусский                                      1
Français|English                                     1
Name: count, dtype: int64
-----------------------------------
status
Released    18
Name: count, dtype: int64
-----------------------------------
tagline
Avenge the fallen.                                                            1
Enter the world of Pandora.                                                   1
Every generation has a story.                                                 1
An entire universe. Once and for all.                                         1
Nothing on earth could come between them.                                     1
The park is open.                                                             1
The king has returned.                                                        1
Some assembly required.                                                       1
Vengeance hits home.                                                          1
A new age has come.                                                           1
Long live the king.                                                           1
It all ends.                                                                  1
Let the past die.                                                             1
The past is not what it seems.                                                1
The park is gone.                                                             1
Who will save the day? The ice guy? The nice guy? The snow man? Or no man?    1
Be our guest.                                                                 1
It's been too long, dahlings.                                                 1
Name: count, dtype: int64
-----------------------------------
title
Avengers: Endgame                               1
Avatar                                          1
Star Wars: The Force Awakens                    1
Avengers: Infinity War                          1
Titanic                                         1
Jurassic World                                  1
The Lion King                                   1
The Avengers                                    1
Furious 7                                       1
Avengers: Age of Ultron                         1
Black Panther                                   1
Harry Potter and the Deathly Hallows: Part 2    1
Star Wars: The Last Jedi                        1
Frozen II                                       1
Jurassic World: Fallen Kingdom                  1
Frozen                                          1
Beauty and the Beast                            1
Incredibles 2                                   1
Name: count, dtype: int64
-----------------------------------
vote_average
8.200    1
7.600    1
7.240    1
8.245    1
7.900    1
6.703    1
7.090    1
8.080    1
7.209    1
7.278    1
7.400    1
8.100    1
6.700    1
7.222    1
6.500    1
7.200    1
7.000    1
7.452    1
Name: count, dtype: int64
-----------------------------------
vote_count
28977.0    1
34826.0    1
21003.0    1
33133.0    1
27878.0    1
21994.0    1
10950.0    1
40007.0    1
11544.0    1
25161.0    1
24083.0    1
22554.0    1
16765.0    1
10509.0    1
13069.0    1
17959.0    1
16211.0    1
14009.0    1
Name: count, dtype: int64
-----------------------------------
collection_id
86311.0     4
10.0        2
328.0       2
386382.0    2
87096.0     1
762512.0    1
9485.0      1
529892.0    1
1241.0      1
468222.0    1
Name: count, dtype: int64
-----------------------------------
collection_name
The Avengers Collection                4
Star Wars Collection                   2
Jurassic Park Collection               2
Frozen Collection                      2
Avatar Collection                      1
The Lion King (Reboot) Collection      1
The Fast and the Furious Collection    1
Black Panther Collection               1
Harry Potter Collection                1
The Incredibles Collection             1
Name: count, dtype: int64
-----------------------------------

#### Handling Missing & Incorrect Data

5. Convert column datatypes:
   - `'budget'`, `'id'`, `'popularity'` → Numeric (set invalid values to `NaN`)

In [13]:
columns = ['budget', 'id', 'popularity']
for col in columns:
    print(df[f"{col}"].dtype)

float64
float64
float64

**Observation:** The three columns above seem to be of **Numeric** value already.

- `'release_date'` → Convert to datetime

In [14]:
df["release_date"] = pd.to_datetime(df["release_date"])
df["release_date"]

0    2019-04-24
1    2009-12-16
2    2015-12-15
3    2018-04-25
4    1997-12-18
5    2015-06-06
6    2019-07-12
7    2012-04-25
8    2015-04-01
9    2015-04-22
10   2018-02-13
11   2011-07-12
12   2017-12-13
13   2019-11-20
14   2018-06-06
15   2013-11-20
16   2017-03-16
17   2018-06-14
Name: release_date, dtype: datetime64[us]

6. Replace unrealistic values:
   - Budget / Revenue / Runtime = `0` → Replace with `NaN` or infer from similar movies

In [15]:
cols = ["budget", "revenue", "runtime"]
for col in cols:
    print(df[f"{col}"].value_counts())
    print("----------------------")

budget
200000000.0    3
150000000.0    3
300000000.0    2
356000000.0    1
237000000.0    1
245000000.0    1
260000000.0    1
220000000.0    1
190000000.0    1
235000000.0    1
125000000.0    1
170000000.0    1
160000000.0    1
Name: count, dtype: int64
----------------------
revenue
2.927449e+09    1
2.923706e+09    1
2.068224e+09    1
2.052415e+09    1
2.264162e+09    1
1.671537e+09    1
1.662021e+09    1
1.518816e+09    1
1.515400e+09    1
1.405404e+09    1
1.349926e+09    1
1.341511e+09    1
1.334408e+09    1
1.453683e+09    1
1.310469e+09    1
1.274219e+09    1
1.266116e+09    1
1.243226e+09    1
Name: count, dtype: int64
----------------------
runtime
118.0    2
129.0    2
181.0    1
162.0    1
136.0    1
149.0    1
194.0    1
124.0    1
143.0    1
138.0    1
141.0    1
135.0    1
130.0    1
152.0    1
103.0    1
102.0    1
Name: count, dtype: int64
----------------------

**Observation:** There doesn't appear to be unrealistic values among these columns.

- Convert `'budget'` and `'revenue'` to million USD

In [16]:
cols = ["budget", "revenue"]

for col in cols:
    df[col] = round((df[col] / 1_000_000), 2)

In [17]:
df[["budget", "revenue"]]

    budget  revenue
0    356.0  2927.45
1    237.0  2923.71
2    245.0  2068.22
3    300.0  2052.42
4    200.0  2264.16
5    150.0  1671.54
6    260.0  1662.02
7    220.0  1518.82
8    190.0  1515.40
9    235.0  1405.40
10   200.0  1349.93
11   125.0  1341.51
12   300.0  1334.41
13   150.0  1453.68
14   170.0  1310.47
15   150.0  1274.22
16   160.0  1266.12
17   200.0  1243.23

- Movies with `vote_count = 0` → Analyze their `vote_average` and adjust accordingly

In [18]:
df["vote_count"].value_counts()

vote_count
28977.0    1
34826.0    1
21003.0    1
33133.0    1
27878.0    1
21994.0    1
10950.0    1
40007.0    1
11544.0    1
25161.0    1
24083.0    1
22554.0    1
16765.0    1
10509.0    1
13069.0    1
17959.0    1
16211.0    1
14009.0    1
Name: count, dtype: int64

**Observation"** There doesn't appear to be a movie with a vote count of 0.

- `'overview'` and `'tagline'` → Replace known placeholders (e.g., `'No Data'`) with `NaN`

In [19]:
cols = ["overview", "tagline"]
for col in cols:
    print(df[f"{col}"].value_counts())
    print("----------------------")

overview
After the devastating events of Avengers: Infinity War, the universe is in ruins due to the efforts of the Mad Titan, Thanos. With the help of remaining allies, the Avengers must assemble once more in order to undo Thanos' actions and restore order to the universe once and for all, no matter what consequences may be in store.                                                                                                                                                                                                                                            1
In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization.                                                                                                                                                                                                                                                                                                                                                                                                    1
Thirty years after defeating the Galactic Empire, Han Solo and his allies face a new threat from the evil Kylo Ren and his army of Stormtroopers.                                                                                                                                                                                                                                                                                                                                                                                                                                  1
As the Avengers and their allies have continued to protect the world from threats too large for any one hero to handle, a new danger has emerged from the cosmic shadows: Thanos. A despot of intergalactic infamy, his goal is to collect all six Infinity Stones, artifacts of unimaginable power, and use them to inflict his twisted will on all of reality. Everything the Avengers have fought for has led up to this moment - the fate of Earth and existence itself has never been more uncertain.                                                                         1
101-year-old Rose DeWitt Bukater tells the story of her life aboard the Titanic, 84 years later. A young Rose boards the ship with her mother and fiancé. Meanwhile, Jack Dawson and Fabrizio De Rossi win third-class tickets aboard the ship. Rose tells the whole story from Titanic's departure through to its death—on its first and last voyage—on April 15, 1912.                                                                                                                                                                                                           1
Twenty-two years after the events of Jurassic Park, Isla Nublar now features a fully functioning dinosaur theme park, Jurassic World, as originally envisioned by John Hammond.                                                                                                                                                                                                                                                                                                                                                                                                    1
Simba idolizes his father, King Mufasa, and takes to heart his own royal destiny. But not everyone in the kingdom celebrates the new cub's arrival. Scar, Mufasa's brother—and former heir to the throne—has plans of his own. The battle for Pride Rock is ravaged with betrayal, tragedy and drama, ultimately resulting in Simba's exile. With help from a curious pair of newfound friends, Simba will have to figure out how to grow up and take back what is rightfully his.                                                                                                 1
When an unexpected enemy emerges and threatens global safety and security, Nick Fury, director of the international peacekeeping agency known as S.H.I.E.L.D., finds himself in need of a team to pull the world back from the brink of disaster. Spanning the globe, a daring recruitment effort begins!                                                                                                                                                                                                                                                                          1
Deckard Shaw seeks revenge against Dominic Toretto and his family for his comatose brother.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        1
When Tony Stark tries to jumpstart a dormant peacekeeping program, things go awry and Earth’s Mightiest Heroes are put to the ultimate test as the fate of the planet hangs in the balance. As the villainous Ultron emerges, it is up to The Avengers to stop him from enacting his terrible plans, and soon uneasy alliances and unexpected action pave the way for an epic and unique global adventure.                                                                                                                                                                         1
King T'Challa returns home to the reclusive, technologically advanced African nation of Wakanda to serve as his country's new leader. However, T'Challa soon finds that he is challenged for the throne by factions within his own country as well as without. Using powers reserved to Wakandan kings, T'Challa assumes the Black Panther mantle to join with ex-girlfriend Nakia, the queen-mother, his princess-kid sister, members of the Dora Milaje (the Wakandan 'special forces') and an American secret agent, to prevent Wakanda from being dragged into a world war.    1
Harry, Ron and Hermione continue their quest to vanquish the evil Voldemort once and for all. Just as things begin to look hopeless for the young wizards, Harry discovers a trio of magical objects that endow him with powers to rival Voldemort's formidable skills.                                                                                                                                                                                                                                                                                                            1
Rey develops her newly discovered abilities with the guidance of Luke Skywalker, who is unsettled by the strength of her powers. Meanwhile, the Resistance prepares to do battle with the First Order.                                                                                                                                                                                                                                                                                                                                                                             1
Elsa, Anna, Kristoff and Olaf head far into the forest to learn the truth about an ancient mystery of their kingdom.                                                                                                                                                                                                                                                                                                                                                                                                                                                               1
Three years after Jurassic World was destroyed, Isla Nublar now sits abandoned. When the island's dormant volcano begins roaring to life, Owen and Claire mount a campaign to rescue the remaining dinosaurs from this extinction-level event.                                                                                                                                                                                                                                                                                                                                     1
Young princess Anna of Arendelle dreams about finding true love at her sister Elsa’s coronation. Fate takes her on a dangerous journey in an attempt to end the eternal winter that has fallen over the kingdom. She's accompanied by ice delivery man Kristoff, his reindeer Sven, and snowman Olaf. On an adventure where she will find out what friendship, courage, family, and true love really means.                                                                                                                                                                        1
A live-action adaptation of Disney's version of the classic tale of a cursed prince and a beautiful young woman who helps him break the spell.                                                                                                                                                                                                                                                                                                                                                                                                                                     1
Elastigirl springs into action to save the day, while Mr. Incredible faces his greatest challenge yet – taking care of the problems of his three children.                                                                                                                                                                                                                                                                                                                                                                                                                         1
Name: count, dtype: int64
----------------------
tagline
Avenge the fallen.                                                            1
Enter the world of Pandora.                                                   1
Every generation has a story.                                                 1
An entire universe. Once and for all.                                         1
Nothing on earth could come between them.                                     1
The park is open.                                                             1
The king has returned.                                                        1
Some assembly required.                                                       1
Vengeance hits home.                                                          1
A new age has come.                                                           1
Long live the king.                                                           1
It all ends.                                                                  1
Let the past die.                                                             1
The past is not what it seems.                                                1
The park is gone.                                                             1
Who will save the day? The ice guy? The nice guy? The snow man? Or no man?    1
Be our guest.                                                                 1
It's been too long, dahlings.                                                 1
Name: count, dtype: int64
----------------------

**Observation:** It appears that there are no invalid values in those 2 columns.

7. Remove duplicates and drop rows with unknown `'id'` or `'title'`

In [20]:
cols = ["id", "title"]
for col in cols:
    print(df[f"{col}"].value_counts())
    print("----------------------")

id
299534.0    1
19995.0     1
140607.0    1
299536.0    1
597.0       1
135397.0    1
420818.0    1
24428.0     1
168259.0    1
99861.0     1
284054.0    1
12445.0     1
181808.0    1
330457.0    1
351286.0    1
109445.0    1
321612.0    1
260513.0    1
Name: count, dtype: int64
----------------------
title
Avengers: Endgame                               1
Avatar                                          1
Star Wars: The Force Awakens                    1
Avengers: Infinity War                          1
Titanic                                         1
Jurassic World                                  1
The Lion King                                   1
The Avengers                                    1
Furious 7                                       1
Avengers: Age of Ultron                         1
Black Panther                                   1
Harry Potter and the Deathly Hallows: Part 2    1
Star Wars: The Last Jedi                        1
Frozen II                                       1
Jurassic World: Fallen Kingdom                  1
Frozen                                          1
Beauty and the Beast                            1
Incredibles 2                                   1
Name: count, dtype: int64
----------------------

**Observation:** It appears that there's no duplicate or invalid values in those 2 columns.

8. Keep only rows where at least 10 columns have non-`NaN` values

In [21]:
# Use numpy to check which rows have NaN values:
rows_with_nulls = np.any(df.isna(), axis=1)

print(rows_with_nulls)

0     False
1     False
2     False
3     False
4      True
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16     True
17    False
dtype: bool

In [22]:
# Take a look at the rows with NaN values:
print(df.iloc[4])
print("------------------------------------------------------------------------------------------------")
print(df.iloc[16])

budget                                                              200.0
genres                                                      Drama|Romance
id                                                                  597.0
origin_country                                                       [US]
original_language                                                      en
overview                101-year-old Rose DeWitt Bukater tells the sto...
popularity                                                        39.3321
production_companies    Paramount Pictures|20th Century Fox|Lightstorm...
production_countries                             United States of America
release_date                                          1997-12-18 00:00:00
revenue                                                           2264.16
runtime                                                             194.0
softcore                                                            False
spoken_languages        English|Français|Deutsch|svenska|Italiano|Pусский
status                                                           Released
tagline                         Nothing on earth could come between them.
title                                                             Titanic
vote_average                                                          7.9
vote_count                                                        27878.0
collection_id                                                         NaN
collection_name                                                       NaN
Name: 4, dtype: object
------------------------------------------------------------------------------------------------
budget                                                              160.0
genres                                             Family|Fantasy|Romance
id                                                               321612.0
origin_country                                                       [US]
original_language                                                      en
overview                A live-action adaptation of Disney's version o...
popularity                                                         45.353
production_companies                Walt Disney Pictures|Mandeville Films
production_countries                             United States of America
release_date                                          2017-03-16 00:00:00
revenue                                                           1266.12
runtime                                                             129.0
softcore                                                            False
spoken_languages                                         Français|English
status                                                           Released
tagline                                                     Be our guest.
title                                                Beauty and the Beast
vote_average                                                          7.0
vote_count                                                        16211.0
collection_id                                                         NaN
collection_name                                                       NaN
Name: 16, dtype: object

**Observation:** Only 2 rows have ``NaN`` values, but they are not more than 2 for both cases. We will keep the rows.

9. Filter to include only `'Released'` movies, then drop `'status'`

In [23]:
df["status"].value_counts()

status
Released    18
Name: count, dtype: int64

In [24]:
# Since all the movies were "Released", we will then drop the "status" column
df = df.drop(columns=["status"])
df.columns

Index(['budget', 'genres', 'id', 'origin_country', 'original_language',
       'overview', 'popularity', 'production_companies',
       'production_countries', 'release_date', 'revenue', 'runtime',
       'softcore', 'spoken_languages', 'tagline', 'title', 'vote_average',
       'vote_count', 'collection_id', 'collection_name'],
      dtype='str')

#### Reorder & Finalize DataFrame

10. Reorder columns:

```python
['id', 'title', 'tagline', 'release_date', 'genres', 'belongs_to_collection',
 'original_language', 'budget_musd', 'revenue_musd', 'production_companies',
 'production_countries', 'vote_count', 'vote_average', 'popularity', 'runtime',
 'overview', 'spoken_languages', 'poster_path', 'cast', 'cast_size', 'director', 'crew_size']
```
11. Reset index

In [26]:
df = df.reindex(columns=['id', 'title', 'tagline', 'release_date', 'genres', 'collection_id', 'collection_name',
 'original_language', 'budget', 'revenue', 'production_companies', "origin_country", "softcore",
 'production_countries', 'vote_count', 'vote_average', 'popularity', 'runtime',
 'overview', 'spoken_languages'])

In [27]:
df.head()

,id,title,tagline,release_date,genres,collection_id,collection_name,original_language,budget,revenue,production_companies,origin_country,softcore,production_countries,vote_count,vote_average,popularity,runtime,overview,spoken_languages
0,299534.0,Avengers: Endgame,Avenge the fallen.,2019-04-24,Adventure|Science Fiction|Action,86311.0,The Avengers Collection,en,356.0,2927.45,Marvel Studios,[US],False,United States of America,28977.0,8.200,96.8577,181.0,After the devastating events of Avengers: Infi...,English|日本語|
1,19995.0,Avatar,Enter the world of Pandora.,2009-12-16,Science Fiction|Action|Adventure,87096.0,Avatar Collection,en,237.0,2923.71,Dune Entertainment|Lightstorm Entertainment|20...,[US],False,United States of America|United Kingdom,34826.0,7.600,41.8923,162.0,"In the 22nd century, a paraplegic Marine is di...",English|Español
2,140607.0,Star Wars: The Force Awakens,Every generation has a story.,2015-12-15,Adventure|Action|Science Fiction,10.0,Star Wars Collection,en,245.0,2068.22,Lucasfilm Ltd.|Bad Robot,[US],False,United States of America,21003.0,7.240,25.1323,136.0,Thirty years after defeating the Galactic Empi...,English
3,299536.0,Avengers: Infinity War,An entire universe. Once and for all.,2018-04-25,Adventure|Action|Science Fiction,86311.0,The Avengers Collection,en,300.0,2052.42,Marvel Studios,[US],False,United States of America,33133.0,8.245,93.1399,149.0,As the Avengers and their allies have continue...,English|
4,597.0,Titanic,Nothing on earth could come between them.,1997-12-18,Drama|Romance,NaN,NaN,en,200.0,2264.16,Paramount Pictures|20th Century Fox|Lightstorm...,[US],False,United States of America,27878.0,7.900,39.3321,194.0,101-year-old Rose DeWitt Bukater tells the sto...,English|Français|Deutsch|svenska|Italiano|Pусский